import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import 'react-loading-skeleton/dist/skeleton.css';

import ReactQueryProvider from './providers/QueryProvider';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'StarSoft Challenge',
  description: 'Generated by NextJS and created by Felipe André',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${poppins.variable}`}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
